// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcknVfoyZqydxZ7YL_VrZy3Nvs7Qbffnc',
    appId: '1:36121048027:web:a87e7d9ce0cbbd61f06dfe',
    messagingSenderId: '36121048027',
    projectId: 'comar-94a8c',
    authDomain: 'comar-94a8c.firebaseapp.com',
    storageBucket: 'comar-94a8c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBreu0bnAYIOjZewb8Vwu771JiQz9Ny0ts',
    appId: '1:36121048027:android:6a887ab458971772f06dfe',
    messagingSenderId: '36121048027',
    projectId: 'comar-94a8c',
    storageBucket: 'comar-94a8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBFBa4QfGnjTOTulgF9NJqxOMArFmIhws',
    appId: '1:36121048027:ios:46495396e28b457cf06dfe',
    messagingSenderId: '36121048027',
    projectId: 'comar-94a8c',
    storageBucket: 'comar-94a8c.appspot.com',
    iosBundleId: 'com.example.comarInsurance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBFBa4QfGnjTOTulgF9NJqxOMArFmIhws',
    appId: '1:36121048027:ios:b096119b034aa4fdf06dfe',
    messagingSenderId: '36121048027',
    projectId: 'comar-94a8c',
    storageBucket: 'comar-94a8c.appspot.com',
    iosBundleId: 'com.example.comarInsurance.RunnerTests',
  );
}
